sudo: required
dist: trusty

language: python
python:
- '2.7'

env:
  global:
    - ANSIBLE_STDOUT_CALLBACK=debug
  matrix:
  - ANSIBLE_REF=devel
  - ANSIBLE_REF=stable-2.2

install:
- travis_retry wget https://raw.githubusercontent.com/novafloss/ansible-setup/master/ansible-setup
- bash -ex ansible-setup lxd_require
- bash ansible-setup ansible_ref_require $ANSIBLE_REF /usr/bin
- ansible-galaxy install -p . -r test-requirements.yml
- ssh-keygen -f /home/travis/.ssh/id_rsa -N ''

script:
- sg lxd 'ansible-playbook -v test.yml --sudo'
